// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yjbjnldabuytacoyacpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqYmpubGRhYnV5dGFjb3lhY3BkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMTM1NjIsImV4cCI6MjA2NTg4OTU2Mn0.Flv0u7NVN09QyweSJsytm67aWzRR3xvEtinbH2JbnN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);